services:
  web:
    image: "finance-app:dev"
    build:
      target: development_build
      context: .
      args:
        DJANGO_ENV: development
    ports:
      - "8000:8000"
    env_file:
      - .env.web
    depends_on:
      - db
    volumes:
      - .:/code

  db:
    image: postgres:17.2-alpine3.21
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env.pgadmin

volumes:
  postgres_data:
  pgadmin-data: